### ISSUE TITLE
add ig tool link on homepage in the just like megaboxing

### ISSUE THREAD

**Issue by Chitranshmittal** [karx/viragram-homepage#11]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by karx** [comment]
I do not understand a word coming from @Chitranshmittal

Please be more clear and verbose. Thanks
At least maintain some clarity and standard.

**Comment by Chitranshmittal** [comment]
@karx I'm just typing whatever Nitin is telling me to!  he is on my ass!! Most of these issues were already discussed with @IAmSarthakVerma .

And this one about adding IG tool on the site.

**Comment by IAmSarthakVerma** [comment]
@Chitranshmittal 
1. If you're tagging anyone here, please do that with at least some attention, you just tagged some "Sarthak Goel" in your comment above instead of me. I have to edit it for you.
2. The main reason for why @karx asked you guys to create issues for the website here was so that it is documented and we can keep track of what is going on so anything discussed here is only what is meant to be "actually" known to us.
3. If you'll not be more descriptive with the issues I won't be able to understand and I won't be leaving all my work and coming to your seat to clarify. It has to be mentioned and discussed here.
For eg: You have created this issue and then another issue exists here: [https://github.com/karx/viragram-homepage/issues/12](https://github.com/karx/viragram-homepage/issues/12) and I don't see any difference between the two as per my understanding.

**Comment by nitin-c** [comment]
![Screenshot 2019-09-26 at 7 18 20 PM](https://user-images.githubusercontent.com/55408164/65693792-77b97280-e092-11e9-9536-01998d0f4d17.png)
on home page after 
![Screenshot 2019-09-26 at 8 29 19 PM](https://user-images.githubusercontent.com/55408164/65699872-5cebfb80-e09c-11e9-9513-d2c6f5a24b0a.png)
